# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a.nbytes

80

In [ ]:
print(a.size*a.itemsize)

80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [3]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
b=np.arange(1,9)
print(b[::-1])

[8 7 6 5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
c=np.arange(0,9).reshape(3,3)
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=np.array([1,2,0,0,4,0])
print(np.nonzero(a))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.random((3,3,3))
a

array([[[0.49488211, 0.28925855, 0.85416914],
        [0.11531667, 0.11660042, 0.50875917],
        [0.73648289, 0.16755788, 0.85012768]],

       [[0.45982783, 0.74457231, 0.73851635],
        [0.5813281 , 0.1035226 , 0.10913054],
        [0.87945123, 0.93430887, 0.24565635]],

       [[0.05238403, 0.28249524, 0.05670907],
        [0.96417527, 0.06783112, 0.64525005],
        [0.09984548, 0.13000664, 0.59561701]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print(a)
print(np.min(a))
print(np.max(a))

[[0.20737829 0.35151889 0.46432855 0.87220553 0.61817057 0.34230448
  0.48546393 0.90163858 0.78337369 0.66765578]
 [0.40228648 0.55477542 0.20258897 0.3026539  0.71082508 0.57426992
  0.14904767 0.17506127 0.82882028 0.19011773]
 [0.08273859 0.69153323 0.20285579 0.30423926 0.72194888 0.93892139
  0.96798037 0.82762921 0.39650186 0.63408615]
 [0.59925485 0.38117674 0.16641555 0.47287103 0.75710124 0.51782202
  0.5507589  0.89858402 0.09603734 0.29823794]
 [0.47887809 0.30793876 0.07380207 0.29735258 0.96958584 0.36271503
  0.91565536 0.64668546 0.80077027 0.16729576]
 [0.89264847 0.36048793 0.58549711 0.82303567 0.27163148 0.8545125
  0.81663113 0.44971428 0.2944234  0.03767756]
 [0.1360588  0.2331898  0.29118087 0.61989551 0.14973858 0.08662178
  0.75232369 0.80621984 0.38434363 0.52910477]
 [0.26279845 0.24703589 0.25864283 0.20962715 0.21001018 0.87252234
  0.34546748 0.09087476 0.26214845 0.26682787]
 [0.24325662 0.92477714 0.45353725 0.77466893 0.58823336 0.29307565
  0.36857363 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.random(30)
np.mean(a)

0.5110942199406151

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
a=np.ones((3,3))
a[1:-1,1:-1]=0
a

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
a=np.ones((4,4))
d=np.pad(a, pad_width=1, mode='constant',
               constant_values=0)
d

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:

a = np.diag(1+np.arange(4),k=-1)
print(a)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5,5))
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print(a)

[[0.56963909 1.         0.62839532 0.67934321 0.66325495]
 [0.04426649 0.21403024 0.64034554 0.864779   0.        ]
 [0.74810279 0.60126785 0.32948728 0.96350399 0.44851763]
 [0.66066234 0.87298838 0.58520202 0.06980027 0.81272803]
 [0.52031666 0.07532027 0.38375155 0.33692123 0.88428995]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
colr = np.dtype([("r", np.ubyte),("g", np.ubyte),
                  ("b", np.ubyte),("a", np.ubyte)])
colr

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.random.randint(10,size=(5,3))
print(a)
b=np.random.randint(10,size=(3,2))
print(b)
print(np.dot(a,b))

[[5 4 1]
 [2 9 3]
 [5 9 0]
 [2 5 7]
 [8 4 5]]
[[8 4]
 [7 5]
 [8 4]]
[[ 76  44]
 [103  65]
 [103  65]
 [107  61]
 [132  72]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a = np.arange(11)
#a[(3 < a) & (a < 8)] *= -1
a[4:8] = np.negative(a[4:8])
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) error

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-10, +10, 10)
print(a)
np.copysign(np.ceil(np.abs(a)),a)

[ 0.07636623 -8.06154015 -4.03328709  7.74728303  4.27365016  3.012897
 -0.98565426 -0.06287554  4.1754895   7.76439369]


array([ 1., -9., -5.,  8.,  5.,  4., -1., -1.,  5.,  8.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.arange(0, 10)
b = np.arange(5, 15)
print(np.intersect1d(a, b))

[5 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all="ignore")
np.seterr(all='ignore')

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday,today,tomorrow)


2022-02-17 2022-02-18 2022-02-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [4]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [5]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [7]:
c = np.random.uniform(0,10,10)

print (c - c%1)
print (np.floor(c))
print (np.ceil(c)-1)
print (c.astype(int))
print (np.trunc(c))

[8. 5. 6. 7. 3. 1. 2. 4. 8. 2.]
[8. 5. 6. 7. 3. 1. 2. 4. 8. 2.]
[8. 5. 6. 7. 3. 1. 2. 4. 8. 2.]
[8 5 6 7 3 1 2 4 8 2]
[8. 5. 6. 7. 3. 1. 2. 4. 8. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [8]:
iterble = (x for x in range(10))
a = np.fromiter(iterble, float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [9]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [10]:
a = np.random.random(10)
a.sort()
print(a)


[0.2991976  0.41345563 0.51894282 0.55994672 0.6157304  0.69036246
 0.87214953 0.87591221 0.88712811 0.98267741]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [11]:
a = np.random.random(10)
np.add.reduce(a)

3.8805238072365764

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [13]:
a = np.random.randint(0,5,10)
b = np.random.randint(0,5,10)

eq = np.allclose(a,b)
print(eq)

eq = np.array_equal(a,b)
print(eq)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [15]:
a = np.zeros(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [16]:
c = np.random.random((10,2))
a,b = c[:,0], c[:,1]
d = np.sqrt(a**2+b**2)
e = np.arctan2(b,a)
print(d)
print(e)

[0.96348718 1.36718146 0.81357119 0.9489042  0.67023274 0.74409652
 1.03196277 0.63125944 0.30704799 0.20180875]
[1.25025832 0.80164032 1.36981363 1.1610145  1.37452689 0.84877634
 1.26820366 1.27286995 1.1374849  0.22088062]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [17]:
a = np.random.random(10)
a[a.argmax()] = 0
a

array([0.89356932, 0.41605055, 0.47624963, 0.74543726, 0.96669081,
       0.96421212, 0.51038245, 0.84915128, 0.49492149, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [18]:
a = np.zeros((5,5), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [20]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[ 3.35448136e+05, -5.52843422e+06, -1.35555424e+05,
        -7.59746644e+06,  6.77292860e+04],
       [ 4.01971071e+05,  1.61991392e+06,  1.81426284e+04,
         1.72370461e+07, -8.38198923e+04],
       [ 3.70951528e+04,  3.29239490e+05,  1.51796559e+05,
         8.40134405e+04,  1.68398279e+05],
       [-6.67754360e+06,  3.92186950e+05,  5.07760909e+06,
        -2.97390398e+03,  1.00722474e+05],
       [-5.47951107e+07,  3.56325504e+06,  2.80243184e+06,
        -6.87890366e+05,  2.12655063e+04]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [22]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [25]:
import sys
np.set_printoptions(threshold=sys.maxsize)
A = np.ones((5,5))
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [26]:
a = np.arange(10)
b = np.random.uniform(0,10)
index = (np.abs(a-b)).argmin()
print(a[index])

6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [27]:
a = np.ones(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [28]:
a = np.random.random((100,2))
X,Y = np.atleast_2d(a[:,0], a[:,1])
dist = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(dist)

[[0.         0.74730877 0.40178528 0.83861178 0.56108375 0.77366931
  0.32802446 0.71347451 0.43786522 0.02200267 0.78083764 0.60045415
  0.43866218 0.78483359 0.84092088 0.54735669 0.37267122 0.27696504
  0.66680303 0.80560477 0.79327263 0.52692229 0.79609584 0.08477122
  0.90741265 0.57470482 0.17994238 0.15645268 0.39123511 0.15973302
  0.24587188 0.51200589 0.1694845  0.49081494 0.74666218 0.34014662
  0.55555219 0.18742253 0.43863696 0.39736827 0.63770628 0.59109458
  0.27829739 0.52556867 0.23036862 0.23372914 0.11406174 0.37116856
  0.88228535 0.36743791 0.21047507 0.5577209  0.27051851 0.09825431
  0.4661697  0.36997533 0.66066997 0.37297174 0.33881688 0.5661656
  0.63494623 0.72999284 0.41800566 0.57416753 0.89299299 0.22409
  0.60180347 0.53295835 0.44358302 0.43046968 0.741204   0.57747213
  0.5925474  0.38621273 0.66168506 0.74292608 0.32910406 0.47514829
  0.3246982  0.37697225 0.71615885 0.2229306  0.70172478 0.9187883
  0.55545728 0.75535295 0.36629161 0.66343144 0.28494

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [29]:
A = np.arange(10, dtype=np.float32)
A = A.astype(np.int32, copy=False)
print(A)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [31]:
from io import StringIO

a = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
b = np.genfromtxt(a, delimiter=",", dtype=np.int)
print(b)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [32]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
    print(index, value)
for index in np.ndindex(a.shape):
    print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [33]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(X*X+Y*Y)
b, c = 1.0, 0.0
a = np.exp(-( (d-c)**2 / ( 2.0 * b**2 ) ) )
print(a)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [36]:
p = 5
a = np.zeros((10,10))
np.put(a, np.random.choice(range(10*10), p, replace=False),1)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [37]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[-0.14850714  0.12041274  0.25580905  0.2817123  -0.51722843  0.37768327
   0.08103929  0.30046541 -0.28606647 -0.46532002]
 [ 0.01606314  0.09154741 -0.18556747 -0.2410474  -0.16824454  0.26439418
  -0.12930338  0.33711192 -0.2410348   0.25608094]
 [-0.50841623 -0.260695   -0.12108664  0.08855979  0.34974934  0.17678206
  -0.09461401  0.13608368 -0.21095845  0.44459545]
 [ 0.28830294 -0.04052195 -0.08761175 -0.21381509 -0.1084435  -0.38058052
   0.5135077   0.15948791 -0.18935451  0.05902878]
 [-0.13844383  0.25286566 -0.50947599  0.16281186 -0.00108294  0.10315591
   0.26611422  0.33146867 -0.41543555 -0.05197802]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [38]:
a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[6 9 1]
 [3 0 3]
 [5 0 2]]
[[3 0 3]
 [5 0 2]
 [6 9 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [40]:
a = np.random.randint(0,5,(3,3))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [41]:
a = np.random.uniform(0,1,10)
b = 0.5
C = a.flat[np.abs(a - b).argmin()]
print(C)

0.5083859331652912


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [43]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
c = np.nditer([A,B,None])
for x,y,z in c: z[...] = x + y
print(c.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [44]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="name1"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "name1")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [45]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)


np.add.at(a, b, 1)
print(a)

[4. 5. 5. 2. 2. 2. 3. 2. 3. 2.]
[7. 9. 9. 3. 3. 3. 5. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [46]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [47]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [49]:
A = np.random.randint(0,5,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

[[19 26 31 29]
 [31 24 27 23]
 [22 25 28 25]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [50]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54036425 0.46549498 0.41967594 0.64869315 0.40773075 0.58332214
 0.47106483 0.51091928 0.45474113 0.33641941]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [52]:
A = np.random.uniform(0,5,(5,5))
B = np.random.uniform(0,5,(5,5))

 
np.diag(np.dot(A, B))

array([32.07886251, 35.63304053, 24.09796413, 54.54432863, 38.0335781 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [53]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [54]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [60]:
A = np.arange(16).reshape(4,4)
A[[0,1]] = A[[1,0]]
print(A)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [64]:
A = np.random.randint(0,50,(10,3))
F = np.roll(A.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 10) ( 4, 29) ( 9, 21) ( 9, 27) ( 9, 39) ( 9, 45) (10, 29) (11, 23)
 (11, 44) (17, 29) (17, 42) (18, 26) (18, 27) (21, 39) (23, 26) (23, 40)
 (23, 44) (26, 27) (26, 40) (27, 45) (29, 32) (29, 34) (29, 35) (29, 37)
 (29, 42) (32, 37) (33, 36) (33, 42) (34, 35) (36, 42)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [67]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [68]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [69]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [70]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.67494488,  0.20328767, -0.25113471, -0.23240895, -0.60626874,
       -0.89045545,  0.42741136,  0.15778413,  0.81797132,  0.0530391 ,
       -0.96413252, -0.69295846, -0.55679188, -0.95635285, -0.6879333 ,
        0.29111643, -0.81841214, -0.25690055,  0.67634027,  0.80960788,
       -0.7625202 ,  0.20442185, -0.4086693 , -0.3865257 ,  0.33735862,
       -0.5218957 ,  0.62374967, -0.65875108, -0.60076853,  0.62682934,
        0.80526483, -0.37336596, -0.3134872 , -0.05253972, -0.48709406,
       -0.04876096,  0.91107951,  0.4354991 , -0.45218393,  0.82547735,
        0.48035891, -0.83683726, -0.4176713 ,  0.78110881, -0.60969708,
        0.15926609,  0.1904199 , -0.61530229, -0.11953203,  0.52047931,
        0.92980532, -0.00304217,  0.59146246, -0.65383174,  0.63772761,
        0.43141337, -0.83812273,  0.19005574, -0.74906673, -0.262419  ,
        0.12803703, -0.50496778,  0.47688119,  0.72893159, -0.32740969,
       -0.83533668, -0.8465875 , -0.0665336 , -0.28553303,  0.68

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [71]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.20947063  1.16433084  4.79407405  7.81633025  9.95621138  0.2332293
  0.11352828 14.81780612  8.77505725  5.23437322]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [72]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[8.13616089e+00 6.55789364e-01 2.70520090e+00 3.63532112e+00
  3.00595486e+00 1.95764684e+00 8.30302737e+00 1.79461934e+00
  4.64141191e+00 5.89898181e+00]
 [7.10422741e+00 9.99657528e+00 7.38960102e+00 9.72318775e+00
  1.40367892e+01 8.57296187e+00 1.88593201e+01 1.04585076e+01
  1.17479230e+00 1.05730603e+01]
 [7.65168368e+00 4.20482150e+00 3.48984209e-01 1.61499854e+00
  2.03642773e+00 6.55214573e+00 3.10531654e+00 2.83443726e+00
  8.16813191e+00 2.84917234e+00]
 [1.86003532e+01 1.38172899e+01 1.64999768e+01 1.17651144e+00
  1.04084970e+01 2.55135596e+00 1.97304644e+01 1.54104121e+01
  9.38979818e+00 1.96908278e+01]
 [7.04006506e+00 9.50254536e+00 7.07016878e+00 9.53460590e+00
  1.35344749e+01 8.11891024e+00 1.83353425e+01 9.98625002e+00
  8.09032327e-01 1.02540583e+01]
 [7.29241070e+00 6.74882628e-01 2.20673002e+00 4.59332958e+00
  3.60335402e+00 1.20670835e+00 8.56800817e+00 1.71289427e+00
  5.04164762e+00 5.39966970e+00]
 [1.59996279e+01 2.79819357e+00 8.66917250e+00 4.06870127e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [73]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 1 1 3 0 8 7 1 1 9]
 [0 7 8 3 9 3 8 4 1 0]
 [2 6 2 6 1 1 4 2 1 4]
 [3 0 3 1 9 1 0 2 4 6]
 [2 5 6 3 3 6 2 9 1 3]
 [0 9 2 8 4 2 5 8 8 1]
 [9 8 5 7 2 7 1 7 6 6]
 [8 4 0 8 6 7 8 6 0 4]
 [4 3 9 6 7 8 0 4 7 4]
 [1 8 9 5 3 1 3 1 0 2]]
[[0 0 0 0 0]
 [0 9 1 1 3]
 [0 0 7 8 3]
 [0 2 6 2 6]
 [0 3 0 3 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [74]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [75]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # svd = Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [78]:
Z = np.random.randint(0,10,30)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [79]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 3]
   [4 0 4]
   [4 0 2]]

  [[4 3 3]
   [0 4 2]
   [0 2 3]]

  [[3 3 4]
   [4 2 0]
   [2 3 2]]

  [[3 4 0]
   [2 0 1]
   [3 2 3]]

  [[4 0 0]
   [0 1 2]
   [2 3 4]]

  [[0 0 2]
   [1 2 2]
   [3 4 0]]

  [[0 2 2]
   [2 2 0]
   [4 0 4]]

  [[2 2 2]
   [2 0 1]
   [0 4 3]]]


 [[[4 0 4]
   [4 0 2]
   [3 0 4]]

  [[0 4 2]
   [0 2 3]
   [0 4 1]]

  [[4 2 0]
   [2 3 2]
   [4 1 3]]

  [[2 0 1]
   [3 2 3]
   [1 3 0]]

  [[0 1 2]
   [2 3 4]
   [3 0 3]]

  [[1 2 2]
   [3 4 0]
   [0 3 2]]

  [[2 2 0]
   [4 0 4]
   [3 2 2]]

  [[2 0 1]
   [0 4 3]
   [2 2 4]]]


 [[[4 0 2]
   [3 0 4]
   [1 1 2]]

  [[0 2 3]
   [0 4 1]
   [1 2 0]]

  [[2 3 2]
   [4 1 3]
   [2 0 0]]

  [[3 2 3]
   [1 3 0]
   [0 0 4]]

  [[2 3 4]
   [3 0 3]
   [0 4 1]]

  [[3 4 0]
   [0 3 2]
   [4 1 4]]

  [[4 0 4]
   [3 2 2]
   [1 4 3]]

  [[0 4 3]
   [2 2 4]
   [4 3 1]]]


 [[[3 0 4]
   [1 1 2]
   [1 4 2]]

  [[0 4 1]
   [1 2 0]
   [4 2 1]]

  [[4 1 3]
   [2 0 0]
   [2 1 3]]

  [[1 3 0]
   [0 0 4]
   [1 3 2]]

  [[3 0 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [80]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 15  3  5  9]
 [15  1  2 13  3]
 [ 3  2  7 42  3]
 [ 5 13 42  8 13]
 [ 9  3  3 13  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [81]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [83]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)